export const EVENTS = [
  {
    id: "1",
    name: "Conferencia de Liderazgo",
    from: "14 de Julio, 2024",
    to: "14 de Julio, 2024",
    description:
      "No te pierdas nuestra proxima conferencia de liderazgo con oradores invitados especiales.",
    icon: "book",
    image: "https://picsum.photos/200",
    ministrie: "Ministerio de Liderazgo",
    hourInit: "09:00 AM",
    hourEnd: "10:00 AM",
    address: "Iglesia Central, Salon Principal",
  },
  {
    id: "2",
    name: "Conferencia de Liderazgo 2",
    from: "14 de Julio, 2024",
    to: "14 de Julio, 2024",
    description:
      "No te pierdas nuestra proxima conferencia de liderazgo con oradores invitados especiales.",
    icon: "book",
    image: "https://picsum.photos/200",
    ministrie: "Escuela Dominical",
    hourInit: "09:00 AM",
    hourEnd: "10:00 AM",
    address: "Iglesia Central, Salon Principal",
  },
  {
    id: "3",
    name: "Conferencia de Liderazgo 3",
    from: "14 de Julio, 2024",
    to: "14 de Julio, 2024",
    description:
      "No te pierdas nuestra proxima conferencia de liderazgo con oradores invitados especiales.",
    icon: "book",
    image: "https://picsum.photos/200",
    ministrie: "Escuela Dominical",
    hourInit: "09:00 AM",
    hourEnd: "10:00 AM",
    address: "Iglesia Central, Salon Principal",
  },
  {
    id: "4",
    name: "Conferencia de Liderazgo 4",
    from: "14 de Julio, 2024",
    to: "14 de Julio, 2024",
    description:
      "No te pierdas nuestra proxima conferencia de liderazgo con oradores invitados especiales.",
    icon: "book",
    image: "https://picsum.photos/200",
    ministrie: "Escuela Dominical",
    hourInit: "09:00 AM",
    hourEnd: "10:00 AM",
    address: "Iglesia Central, Salon Principal",
  },
  {
    id: "5",
    name: "Conferencia de Liderazgo 5",
    from: "14 de Julio, 2024",
    to: "14 de Julio, 2024",
    description:
      "No te pierdas nuestra proxima conferencia de liderazgo con oradores invitados especiales.",
    icon: "book",
    image: "https://picsum.photos/200",
    ministrie: "Escuela Dominical",
    hourInit: "09:00 AM",
    hourEnd: "10:00 AM",
    address: "Iglesia Central, Salon Principal",
  },
];
